"""CLI entry point for schema-salad-plus-pydantic."""

from __future__ import annotations

import argparse
import sys

from .enhance_docs import enhance_docs
from .orchestrate import generate_from_schema


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        prog="schema-salad-plus-pydantic",
        description="Generate pydantic v2 models or TypeScript interfaces from schema-salad definitions",
    )
    subparsers = parser.add_subparsers(dest="command")

    gen_parser = subparsers.add_parser("generate", help="Generate pydantic models")
    gen_parser.add_argument("schema", help="Schema-salad YAML file")
    gen_parser.add_argument("-o", "--output", help="Output file (default: stdout)")
    gen_parser.add_argument("--copyright", help="Copyright notice")
    gen_parser.add_argument("--parser-info", default="", help="Parser info string")
    gen_parser.add_argument(
        "--strict",
        action="store_true",
        help="Emit models with extra='forbid' (reject unknown fields); default is extra='allow'",
    )
    gen_parser.add_argument(
        "--format",
        choices=["pydantic", "typescript", "effect-schema"],
        default="pydantic",
        help="Output format (default: pydantic)",
    )

    doc_parser = subparsers.add_parser("enhance-docs", help="Enhance schema-salad-doc HTML with pydantic types")
    doc_parser.add_argument("schema", help="Schema-salad YAML file with pydantic annotations")
    doc_parser.add_argument("html", help="HTML file generated by schema-salad-doc")
    doc_parser.add_argument("-o", "--output", help="Output HTML file (default: overwrite input)")

    args = parser.parse_args(argv)

    if args.command == "generate":
        if args.output:
            with open(args.output, "w") as f:
                generate_from_schema(
                    args.schema,
                    f,
                    copyright=args.copyright,
                    parser_info=args.parser_info,
                    strict=args.strict,
                    output_format=args.format,
                )
        else:
            generate_from_schema(
                args.schema,
                sys.stdout,
                copyright=args.copyright,
                parser_info=args.parser_info,
                strict=args.strict,
                output_format=args.format,
            )
    elif args.command == "enhance-docs":
        enhance_docs(args.schema, args.html, args.output)
    else:
        parser.print_help()
        sys.exit(1)
