"""PydanticCodeGen — generates pydantic v2 BaseModel classes from schema-salad."""

from __future__ import annotations

import re
from collections import OrderedDict
from collections.abc import MutableSequence
from io import StringIO
from typing import IO, Any, Final

from schema_salad import schema
from schema_salad.codegen_base import LazyInitDef, TypeDef
from schema_salad.schema import shortname

# Primitive type mappings — we map to Python/pydantic types, not loader classes
_PRIM_PYTHON: Final[dict[str, str]] = {
    "http://www.w3.org/2001/XMLSchema#string": "str",
    "http://www.w3.org/2001/XMLSchema#int": "int",
    "http://www.w3.org/2001/XMLSchema#long": "int",
    "http://www.w3.org/2001/XMLSchema#float": "float",
    "http://www.w3.org/2001/XMLSchema#double": "float",
    "http://www.w3.org/2001/XMLSchema#boolean": "bool",
    "https://w3id.org/cwl/salad#null": "None",
    "https://w3id.org/cwl/salad#Any": "Any",
    "string": "str",
    "int": "int",
    "long": "int",
    "float": "float",
    "double": "float",
    "boolean": "bool",
    "null": "None",
    "Any": "Any",
}

# TypeDefs for primitives (init is the python type string, instance_type is the annotation)
_PRIM_TYPEDEFS: Final[dict[str, TypeDef]] = {
    k: TypeDef(name=v, init=v, instance_type=v) for k, v in _PRIM_PYTHON.items()
}


class PydanticCodeGen:
    """Generate pydantic v2 BaseModel classes from schema-salad definitions.

    Implements the same interface as CodeGenBase but without inheriting from it,
    because schema-salad ships as Cython-compiled .so files which block subclassing
    at instantiation time.
    """

    def __init__(
        self,
        out: IO[str],
        copyright: str | None = None,
        parser_info: str = "",
        salad_version: str = "v1.1",
    ) -> None:
        # CodeGenBase state (reimplemented to avoid Cython inheritance issue)
        self.collected_types: OrderedDict[str, TypeDef] = OrderedDict()
        self.lazy_inits: OrderedDict[str, LazyInitDef] = OrderedDict()
        self.vocab: dict[str, str] = {}

        self.out: Final = out
        self.copyright = copyright
        self.parser_info = parser_info
        self.salad_version = salad_version

        # State tracking
        self._current_class: str = ""
        self._current_extends: list[str] = []
        self._classes: list[str] = []
        self._enum_code: StringIO = StringIO()
        self._class_code: StringIO = StringIO()
        self._enums_emitted: set[str] = set()

        # Per-field pydantic annotation overrides (set by orchestrator before declare_field)
        self._field_pydantic_type: str | None = None
        self._field_pydantic_alias: str | None = None
        self._field_pydantic_discriminator_field: str | None = None
        self._field_pydantic_discriminator_map: str | None = None

        # Track inherited fields per class for filtering
        self._current_class_inherited_from: dict[str, str] = {}

    def declare_type(self, declared_type: TypeDef) -> TypeDef:
        if declared_type not in self.collected_types.values():
            self.collected_types[declared_type.name] = declared_type
        return declared_type

    def add_lazy_init(self, lazy_init: LazyInitDef) -> None:
        self.lazy_inits[lazy_init.name] = lazy_init

    def add_vocab(self, name: str, uri: str) -> None:
        self.vocab[name] = uri

    @staticmethod
    def safe_name(name: str) -> str:
        avn = schema.avro_field_name(name)
        if avn.startswith("anon."):
            avn = avn[5:]
        elif avn and avn[0].isdigit():
            avn = f"_{avn}"
        return avn.replace(".", "_")

    def _python_name(self, name: str) -> str:
        """Convert a field name to a Python-safe identifier."""
        sn = shortname(name)
        if sn in ("class", "in", "type"):
            return f"{sn}_"
        return sn.replace("-", "_")

    def _json_key(self, name: str) -> str:
        """Get the JSON key for a field (the shortname before python-safeing)."""
        return shortname(name)

    def prologue(self) -> None:
        self.out.write("# Auto-generated by schema-salad-plus-pydantic — do not edit.\n")
        if self.copyright:
            self.out.write(f"# Original schema is {self.copyright}.\n")
        self.out.write("""
from __future__ import annotations

import json
from enum import Enum
from pathlib import Path
from typing import Any, Annotated, Literal, Union

from pydantic import BaseModel, ConfigDict, Field, Discriminator, Tag


""")
        self.out.write(f'def parser_info() -> str:\n    return "{self.parser_info}"\n\n\n')
        for td in _PRIM_TYPEDEFS.values():
            self.declare_type(td)

    def begin_class(
        self,
        classname: str,
        extends: MutableSequence[str],
        doc: str,
        abstract: bool,
        field_names: MutableSequence[str],
        idfield: str,
        optional_fields: set[str],
    ) -> None:
        safe = self.safe_name(classname)
        self._current_class = safe
        self._current_extends = [self.safe_name(e) for e in extends]
        self._classes.append(safe)
        self._current_class_inherited_from = {}

        bases = ", ".join(self._current_extends) if self._current_extends else "BaseModel"
        self._class_code.write(f"\nclass {safe}({bases}):\n")

        if doc:
            # Trim and indent docstring
            doc_clean = doc.strip().replace('"""', "'''")
            self._class_code.write(f'    """{doc_clean}"""\n\n')

        self._class_code.write('    model_config = ConfigDict(populate_by_name=True, extra="allow")\n\n')

    def end_class(self, classname: str, field_names: list[str]) -> None:
        self._current_class = ""
        self._current_extends = []
        self._current_class_inherited_from = {}

    def type_loader(
        self,
        type_declaration: list[Any] | dict[str, Any] | str,
        container: str | None = None,
        no_link_check: bool | None = None,
    ) -> TypeDef:
        match type_declaration:
            case MutableSequence():
                # Union type
                parts = []
                for item in type_declaration:
                    td = self.type_loader(item)
                    parts.append(td.instance_type or td.name)
                # Deduplicate while preserving order
                seen: set[str] = set()
                unique_parts: list[str] = []
                for p in parts:
                    if p not in seen:
                        seen.add(p)
                        unique_parts.append(p)
                union_str = " | ".join(unique_parts)
                name = "union_of_" + "_or_".join(unique_parts)
                return self.declare_type(TypeDef(name=name, init=union_str, instance_type=union_str))

            case {"type": "array" | "https://w3id.org/cwl/salad#array", "items": items}:
                if isinstance(items, list):
                    # Array of union
                    inner_parts = []
                    for it in items:
                        td = self.type_loader(it)
                        inner_parts.append(td.instance_type or td.name)
                    inner_str = " | ".join(inner_parts)
                    type_str = f"list[{inner_str}]"
                else:
                    inner = self.type_loader(items)
                    type_str = f"list[{inner.instance_type or inner.name}]"
                return self.declare_type(TypeDef(name=f"array_{type_str}", init=type_str, instance_type=type_str))

            case {
                "type": "enum" | "https://w3id.org/cwl/salad#enum",
                "symbols": symbols,
                "name": name,
                **rest,
            }:
                safe = self.safe_name(name)
                for sym in symbols:
                    self.add_vocab(shortname(sym), sym)

                if len(symbols) == 1:
                    # Single-symbol enum -> Literal
                    sym_val = shortname(symbols[0])
                    type_str = f'Literal["{sym_val}"]'
                    return self.declare_type(TypeDef(name=f"{safe}Loader", init=type_str, instance_type=type_str))
                else:
                    # Multi-symbol -> Enum class
                    if safe not in self._enums_emitted:
                        self._enums_emitted.add(safe)
                        self._enum_code.write(f"\nclass {safe}(str, Enum):\n")
                        doc = rest.get("doc", "")
                        if doc:
                            if isinstance(doc, list):
                                doc = "\n".join(doc)
                            doc_clean = str(doc).strip().replace('"""', "'''")
                            self._enum_code.write(f'    """{doc_clean}"""\n\n')
                        for sym in symbols:
                            sym_short = shortname(sym)
                            # Make valid Python identifier
                            py_name = sym_short.replace("-", "_").replace(".", "_")
                            self._enum_code.write(f'    {py_name} = "{sym_short}"\n')
                        self._enum_code.write("\n")

                    return self.declare_type(TypeDef(name=f"{safe}Loader", init=safe, instance_type=safe))

            case {"type": "record" | "https://w3id.org/cwl/salad#record", "name": name, **rest}:
                safe = self.safe_name(name)
                return self.declare_type(
                    TypeDef(
                        name=f"{safe}Loader",
                        init=safe,
                        instance_type=safe,
                        abstract=bool(rest.get("abstract", False)),
                    )
                )

            case {
                "type": "union" | "https://w3id.org/cwl/salad#union",
                "name": name,
                "names": list(names),
            }:
                safe = self.safe_name(name)
                loader_name = f"{safe}Loader"
                parts = []
                for n in names:
                    td = self.type_loader(n)
                    parts.append(td.instance_type or td.name)
                union_str = " | ".join(parts)
                return self.declare_type(TypeDef(name=loader_name, init=union_str, instance_type=union_str))

            case str(decl) if decl in _PRIM_TYPEDEFS:
                return _PRIM_TYPEDEFS[decl]

            case str(decl):
                safe = self.safe_name(decl)
                loader_key = f"{safe}Loader"
                if loader_key in self.collected_types:
                    return self.collected_types[loader_key]
                # Forward reference — return a TypeDef pointing to the class name
                return self.declare_type(TypeDef(name=loader_key, init=safe, instance_type=safe))

            case _:
                raise ValueError(f"Unhandled type declaration: {type_declaration}")

    def set_field_annotations(
        self,
        pydantic_type: str | None = None,
        pydantic_alias: str | None = None,
        discriminator_field: str | None = None,
        discriminator_map: str | None = None,
    ) -> None:
        """Set pydantic annotation overrides for the next declare_field call."""
        self._field_pydantic_type = pydantic_type
        self._field_pydantic_alias = pydantic_alias
        self._field_pydantic_discriminator_field = discriminator_field
        self._field_pydantic_discriminator_map = discriminator_map

    def _clear_field_annotations(self) -> None:
        self._field_pydantic_type = None
        self._field_pydantic_alias = None
        self._field_pydantic_discriminator_field = None
        self._field_pydantic_discriminator_map = None

    def declare_field(
        self,
        name: str,
        fieldtype: TypeDef,
        doc: str | None,
        optional: bool,
        subscope: str | None,
    ) -> None:
        # Skip inherited fields
        inherited_from = self._current_class_inherited_from.get(shortname(name))
        if inherited_from and inherited_from in self._current_extends:
            self._clear_field_annotations()
            return

        json_key = self._json_key(name)
        py_name = self._python_name(name)

        # Determine type annotation
        if self._field_pydantic_type:
            type_ann = self._field_pydantic_type
        else:
            type_ann = fieldtype.instance_type or fieldtype.name
            if optional and "None" not in type_ann:
                type_ann = f"{type_ann} | None"

        # Build Field() kwargs
        field_kwargs: dict[str, str] = {}

        # Alias: explicit pydantic:alias takes priority, then auto-detect from name mismatch
        if self._field_pydantic_alias:
            field_kwargs["alias"] = f'"{self._field_pydantic_alias}"'
        elif py_name != json_key:
            field_kwargs["alias"] = f'"{json_key}"'

        # Description
        if doc:
            doc_escaped = doc.strip().replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")
            if len(doc_escaped) > 200:
                doc_escaped = doc_escaped[:197] + "..."
            field_kwargs["description"] = f'"{doc_escaped}"'

        # Default for optional fields
        if optional:
            default = "None"
        else:
            default = None

        # Single-symbol Literal fields (discriminators) get a default value
        literal_match = re.match(r'^Literal\["(.+)"\]$', type_ann)
        if literal_match and default is None:
            default = f'"{literal_match.group(1)}"'

        # Build discriminator annotation if present
        if self._field_pydantic_discriminator_field and self._field_pydantic_discriminator_map:
            disc_field = self._field_pydantic_discriminator_field
            disc_map_str = self._field_pydantic_discriminator_map
            # Generate the discriminator function name
            disc_func = f"_discriminate_{py_name}"
            self._class_code.write(f"    # Discriminated union on '{disc_field}'\n")
            type_ann_line = f"    {py_name}: Annotated[{type_ann}, Discriminator({disc_func})]"
        else:
            disc_func = None
            disc_field = None
            disc_map_str = None

            if field_kwargs or default is not None:
                kwargs_parts = []
                if default is not None:
                    kwargs_parts.append(f"default={default}")
                kwargs_parts.extend(f"{k}={v}" for k, v in field_kwargs.items())
                field_call = f"Field({', '.join(kwargs_parts)})"
                type_ann_line = f"    {py_name}: {type_ann} = {field_call}"
            else:
                type_ann_line = f"    {py_name}: {type_ann}"

        self._class_code.write(f"{type_ann_line}\n")

        # If we used a discriminator, emit the discriminator function right after the class
        if disc_func and disc_field and disc_map_str:
            # Store for later emission (after all classes)
            if not hasattr(self, "_deferred_discriminators"):
                self._deferred_discriminators: list[tuple[str, str, str, str]] = []
            self._deferred_discriminators.append((disc_func, disc_field, disc_map_str, self._current_class))

        self._clear_field_annotations()

    def declare_id_field(
        self,
        name: str,
        fieldtype: TypeDef,
        doc: str | None,
        optional: bool,
    ) -> None:
        # Treat @id fields as normal fields in pydantic
        self.declare_field(name, fieldtype, doc, optional, None)

    def uri_loader(
        self,
        inner: TypeDef,
        scoped_id: bool,
        vocab_term: bool,
        ref_scope: int | None,
        no_link_check: bool | None = None,
    ) -> TypeDef:
        return inner

    def idmap_loader(self, field: str, inner: TypeDef, map_subject: str, map_predicate: str | None) -> TypeDef:
        return inner

    def typedsl_loader(self, inner: TypeDef, ref_scope: int | None) -> TypeDef:
        return inner

    def secondaryfilesdsl_loader(self, inner: TypeDef) -> TypeDef:
        return inner

    def epilogue(self, root_loader: TypeDef) -> None:
        # Emit enums first
        self.out.write(self._enum_code.getvalue())

        # Emit discriminator functions before classes (they need to be defined before use)
        if hasattr(self, "_deferred_discriminators"):
            for disc_func, disc_field, disc_map_str, classname in self._deferred_discriminators:
                self.out.write(f"\ndef {disc_func}(v: Any) -> str:\n")
                self.out.write(f"    disc_map = {disc_map_str}\n")
                self.out.write("    if isinstance(v, dict):\n")
                self.out.write(f'        disc_val = v.get("{disc_field}")\n')
                self.out.write("    else:\n")
                self.out.write(f'        disc_val = getattr(v, "{disc_field}", None)\n')
                self.out.write("    return disc_map.get(disc_val, disc_val)\n\n")

        # Emit classes
        self.out.write(self._class_code.getvalue())

        # model_rebuild() for all classes
        self.out.write("\n# Rebuild models for forward references\n")
        for cls in self._classes:
            self.out.write(f"{cls}.model_rebuild()\n")

        # Emit load_document convenience function
        root_type = root_loader.instance_type or root_loader.name
        self.out.write(f"""

def load_document(path: str | Path) -> {root_type}:
    \"\"\"Load and validate a document from a JSON file.\"\"\"
    with open(path) as f:
        data = json.load(f)
    if isinstance(data, list):
        return [_load_single(item) for item in data]
    return _load_single(data)


def _load_single(data: dict[str, Any]) -> {root_type}:
    \"\"\"Load a single document dict.\"\"\"
""")
        # If root_type is a union, need to try each
        if " | " in root_type:
            parts = [p.strip() for p in root_type.split("|") if p.strip() != "None" and "list[" not in p]
            if parts:
                self.out.write(f"    return {parts[0]}.model_validate(data)\n")
            else:
                self.out.write("    raise ValueError('Cannot load document')\n")
        else:
            self.out.write(f"    return {root_type}.model_validate(data)\n")

    def mark_field_inherited(self, field_shortname: str, inherited_from: str) -> None:
        """Mark a field as inherited from a parent class."""
        parent_safe = self.safe_name(inherited_from)
        self._current_class_inherited_from[field_shortname] = parent_safe
