"""PydanticCodeGen — generates pydantic v2 BaseModel classes from schema-salad."""

from __future__ import annotations

import ast
import re
from collections.abc import MutableSequence
from io import StringIO
from typing import IO, Final

from schema_salad.codegen_base import TypeDef
from schema_salad.schema import shortname

from .codegen_base import CodeGenBase, split_top_level

# Primitive type mappings — we map to Python/pydantic types, not loader classes
_PRIM_PYTHON: Final[dict[str, str]] = {
    "http://www.w3.org/2001/XMLSchema#string": "str",
    "http://www.w3.org/2001/XMLSchema#int": "int",
    "http://www.w3.org/2001/XMLSchema#long": "int",
    "http://www.w3.org/2001/XMLSchema#float": "float",
    "http://www.w3.org/2001/XMLSchema#double": "float",
    "http://www.w3.org/2001/XMLSchema#boolean": "bool",
    "https://w3id.org/cwl/salad#null": "None",
    "https://w3id.org/cwl/salad#Any": "Any",
    "string": "str",
    "int": "int",
    "long": "int",
    "float": "float",
    "double": "float",
    "boolean": "bool",
    "null": "None",
    "Any": "Any",
}

# TypeDefs for primitives (init is the python type string, instance_type is the annotation)
_PRIM_TYPEDEFS: Final[dict[str, TypeDef]] = {
    k: TypeDef(name=v, init=v, instance_type=v) for k, v in _PRIM_PYTHON.items()
}


class PydanticCodeGen(CodeGenBase):
    """Generate pydantic v2 BaseModel classes from schema-salad definitions."""

    def __init__(
        self,
        out: IO[str],
        copyright: str | None = None,
        parser_info: str = "",
        salad_version: str = "v1.1",
        strict: bool = False,
    ) -> None:
        super().__init__(out, copyright=copyright, parser_info=parser_info, salad_version=salad_version)
        self._extra: Final[str] = "forbid" if strict else "allow"

        self._enum_code: StringIO = StringIO()
        self._class_code: StringIO = StringIO()

    # ── backend-specific type helpers ──

    def _primitive_typedefs(self) -> dict[str, TypeDef]:
        return _PRIM_TYPEDEFS

    def _array_type_str(self, inner: str) -> str:
        return f"list[{inner}]"

    def _single_symbol_type_str(self, symbol_value: str) -> str:
        return f'Literal["{symbol_value}"]'

    def _emit_enum(self, safe: str, symbols: list[str], doc: str) -> None:
        self._enum_code.write(f"\nclass {safe}(str, Enum):\n")
        if doc:
            doc_clean = doc.strip().replace('"""', "'''")
            self._enum_code.write(f'    """{doc_clean}"""\n\n')
        for sym in symbols:
            py_name = sym.replace("-", "_").replace(".", "_")
            self._enum_code.write(f'    {py_name} = "{sym}"\n')
        self._enum_code.write("\n")

    # ── output methods ──

    def _python_name(self, name: str) -> str:
        """Convert a field name to a Python-safe identifier."""
        sn = shortname(name)
        if sn in ("class", "in", "type"):
            return f"{sn}_"
        return sn.replace("-", "_")

    def _json_key(self, name: str) -> str:
        """Get the JSON key for a field (the shortname before python-safeing)."""
        return shortname(name)

    def prologue(self) -> None:
        self.out.write("# Auto-generated by schema-salad-plus-pydantic — do not edit.\n")
        if self.copyright:
            self.out.write(f"# Original schema is {self.copyright}.\n")
        self.out.write("""
from __future__ import annotations

import json
from enum import Enum
from pathlib import Path
from typing import Any, Annotated, Literal, Union

from pydantic import BaseModel, ConfigDict, Field, Discriminator, Tag


""")
        self.out.write(f'def parser_info() -> str:\n    return "{self.parser_info}"\n\n\n')
        for td in _PRIM_TYPEDEFS.values():
            self.declare_type(td)

    def begin_class(
        self,
        classname: str,
        extends: MutableSequence[str],
        doc: str,
        abstract: bool,
        field_names: MutableSequence[str],
        idfield: str,
        optional_fields: set[str],
    ) -> None:
        safe = self.safe_name(classname)
        self._current_class = safe
        self._current_extends = [self.safe_name(e) for e in extends]
        self._classes.append(safe)
        self._current_class_inherited_from = {}

        bases = ", ".join(self._current_extends) if self._current_extends else "BaseModel"
        self._class_code.write(f"\nclass {safe}({bases}):\n")

        if doc:
            # Trim and indent docstring
            doc_clean = doc.strip().replace('"""', "'''")
            self._class_code.write(f'    """{doc_clean}"""\n\n')

        self._class_code.write(f'    model_config = ConfigDict(populate_by_name=True, extra="{self._extra}")\n\n')

    def end_class(self, classname: str, field_names: list[str]) -> None:
        self._current_class = ""
        self._current_extends = []
        self._current_class_inherited_from = {}

    @staticmethod
    def _build_discriminated_type(type_ann: str, tag_map: dict[str, str], disc_func: str) -> str:
        """Build a pydantic Discriminator-annotated type from a type annotation.

        The Discriminator must wrap only the union of model types, not nullable/list
        wrappers. Each union member gets a Tag annotation.

        Examples::

          None | list[A | B]  -> list[Annotated[..., Discriminator(f)]] | None
          list[A | B] | None  -> list[Annotated[..., Discriminator(f)]] | None
          A | B | None        -> Annotated[..., Discriminator(f)] | None
          A | B               -> Annotated[..., Discriminator(f)]
        """

        def tag_type(t: str) -> str:
            t = t.strip()
            if t in tag_map:
                return f'Annotated[{t}, Tag("{tag_map[t]}")]'
            return t

        def tag_union(union_str: str) -> str:
            parts = [p.strip() for p in union_str.split("|")]
            return " | ".join(tag_type(p) for p in parts)

        # Strip None from the union (may appear at beginning or end)
        top_parts = split_top_level(type_ann, "|")
        non_none = [p.strip() for p in top_parts if p.strip() != "None"]
        nullable = len(non_none) < len(top_parts)

        # Split into branches at top level to handle complex unions like
        # list[A | B] | dict[str, A | B | str]
        branches = [b.strip() for b in non_none]
        applied = False
        for i, branch in enumerate(branches):
            list_match = re.match(r"^list\[(.+)\]$", branch)
            if list_match:
                inner_union = list_match.group(1)
                tagged_inner = tag_union(inner_union)
                branches[i] = f"list[Annotated[{tagged_inner}, Discriminator({disc_func})]]"
                applied = True
                break

        if not applied:
            # No list branch — apply discriminator to the bare union
            core = " | ".join(branches)
            tagged = tag_union(core)
            result = f"Annotated[{tagged}, Discriminator({disc_func})]"
        else:
            result = " | ".join(branches)

        if nullable:
            result = f"{result} | None"

        return result

    def declare_field(
        self,
        name: str,
        fieldtype: TypeDef,
        doc: str | None,
        optional: bool,
        subscope: str | None,
    ) -> None:
        # Skip inherited fields
        inherited_from = self._current_class_inherited_from.get(shortname(name))
        if inherited_from and inherited_from in self._current_extends:
            self._clear_field_annotations()
            return

        json_key = self._json_key(name)
        py_name = self._python_name(name)

        # Determine type annotation
        if self._field_pydantic_type:
            type_ann = self._field_pydantic_type
        else:
            type_ann = fieldtype.instance_type or fieldtype.name
            if optional and "None" not in type_ann:
                type_ann = f"{type_ann} | None"

        # Build Field() kwargs
        field_kwargs: dict[str, str] = {}

        # Alias: explicit pydantic:alias takes priority, then auto-detect from name mismatch
        if self._field_pydantic_alias:
            field_kwargs["alias"] = f'"{self._field_pydantic_alias}"'
        elif py_name != json_key:
            field_kwargs["alias"] = f'"{json_key}"'

        # Description
        if doc:
            doc_escaped = doc.strip().replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")
            if len(doc_escaped) > 200:
                doc_escaped = doc_escaped[:197] + "..."
            field_kwargs["description"] = f'"{doc_escaped}"'

        # Default for optional fields
        if optional:
            default = "None"
        else:
            default = None

        # Single-symbol Literal fields (discriminators) get a default value
        literal_match = re.match(r'^Literal\["(.+)"\]$', type_ann)
        if literal_match and default is None:
            default = f'"{literal_match.group(1)}"'

        # Build discriminator annotation if present
        if self._field_pydantic_discriminator_field and self._field_pydantic_discriminator_map:
            disc_field = self._field_pydantic_discriminator_field
            disc_map_str = self._field_pydantic_discriminator_map
            disc_func = f"_discriminate_{py_name}"
            disc_map = ast.literal_eval(disc_map_str)
            reverse_map = {v: v for v in disc_map.values()}
            # Build the discriminated type annotation. The Discriminator must wrap
            # only the union, not nullable/list wrappers. Pattern:
            #   list[A | B] | None -> list[Annotated[A | B, Discriminator(f)]] | None
            #   A | B | None       -> Annotated[A | B, Discriminator(f)] | None
            #   list[A | B]        -> list[Annotated[A | B, Discriminator(f)]]
            tagged_ann = self._build_discriminated_type(type_ann, reverse_map, disc_func)
            self._class_code.write(f"    # Discriminated union on '{disc_field}'\n")
            if default is not None:
                type_ann_line = f"    {py_name}: {tagged_ann} = {default}"
            else:
                type_ann_line = f"    {py_name}: {tagged_ann}"
        else:
            disc_func = None
            disc_field = None
            disc_map_str = None

            if field_kwargs or default is not None:
                kwargs_parts = []
                if default is not None:
                    kwargs_parts.append(f"default={default}")
                kwargs_parts.extend(f"{k}={v}" for k, v in field_kwargs.items())
                field_call = f"Field({', '.join(kwargs_parts)})"
                type_ann_line = f"    {py_name}: {type_ann} = {field_call}"
            else:
                type_ann_line = f"    {py_name}: {type_ann}"

        self._class_code.write(f"{type_ann_line}\n")

        # If we used a discriminator, emit the discriminator function right after the class
        if disc_func and disc_field and disc_map_str:
            # Store for later emission (after all classes)
            if not hasattr(self, "_deferred_discriminators"):
                self._deferred_discriminators: list[tuple[str, str, str, str, str | None]] = []
            self._deferred_discriminators.append(
                (disc_func, disc_field, disc_map_str, self._current_class, self._field_pydantic_discriminator_default)
            )

        self._clear_field_annotations()

    def declare_id_field(
        self,
        name: str,
        fieldtype: TypeDef,
        doc: str | None,
        optional: bool,
    ) -> None:
        # Treat @id fields as normal fields in pydantic
        self.declare_field(name, fieldtype, doc, optional, None)

    def epilogue(self, root_loader: TypeDef) -> None:
        # Emit enums first
        self.out.write(self._enum_code.getvalue())

        # Emit discriminator functions before classes (they need to be defined before use)
        if hasattr(self, "_deferred_discriminators"):
            for disc_func, disc_field, disc_map_str, classname, disc_default in self._deferred_discriminators:
                # For getattr on model instances, use Python-safe name (e.g. "class" -> "class_")
                py_disc_field = self._python_name(disc_field)
                self.out.write(f"\ndef {disc_func}(v: Any) -> str:\n")
                self.out.write(f"    disc_map: dict[str, str] = {disc_map_str}\n")
                self.out.write("    if isinstance(v, dict):\n")
                self.out.write(f'        disc_val: str = str(v.get("{disc_field}", ""))\n')
                self.out.write("    else:\n")
                self.out.write(f'        disc_val = str(getattr(v, "{py_disc_field}", ""))\n')
                if disc_default:
                    self.out.write(f'    return disc_map.get(disc_val, "{disc_default}")\n\n')
                else:
                    self.out.write("    return disc_map.get(disc_val, disc_val)\n\n")

        # Emit classes
        self.out.write(self._class_code.getvalue())

        # model_rebuild() for all classes
        self.out.write("\n# Rebuild models for forward references\n")
        for cls in self._classes:
            self.out.write(f"{cls}.model_rebuild()\n")

        # Emit load_document convenience function
        root_type = root_loader.instance_type or root_loader.name

        # Extract the single-document types (not list[...]) for _load_single
        if " | " in root_type:
            single_parts = [p.strip() for p in root_type.split("|") if p.strip() != "None" and "list[" not in p]
        else:
            single_parts = [root_type]
        single_type = " | ".join(single_parts) if single_parts else root_type

        self.out.write(f"""

def load_document(path: str | Path) -> {single_type} | list[{single_type}]:
    \"\"\"Load and validate a document from a JSON file.\"\"\"
    with open(path) as f:
        data = json.load(f)
    if isinstance(data, list):
        return [_load_single(item) for item in data]
    return _load_single(data)


def _load_single(data: dict[str, Any]) -> {single_type}:
    \"\"\"Load a single document dict.\"\"\"
""")
        if single_parts:
            self.out.write(f"    return {single_parts[0]}.model_validate(data)\n")
        else:
            self.out.write("    raise ValueError('Cannot load document')\n")
